export const temporalGames = [
  {
    id: 'ps5-gow',
    title: 'God of War Ragnarok',
    price: '$50',
    platform: 'PS5',
    img: 'ps5-gow.jpg',
  },
  {
    id: 'ps5-hl',
    title: 'Hogwarts Legacy',
    price: '$50',
    platform: 'PS5',
    img: 'ps5-hl.jpg',
  },
  {
    id: 'ps5-er',
    title: 'Elden Ring',
    price: '$50',
    platform: 'PS5',
    img: 'ps5-er.jpg',
  },
  {
    id: 'ps5-re8',
    title: 'Resident Evil Village',
    price: '$50',
    platform: 'PS5',
    img: 'ps5-re8.jpg',
  },
  {
    id: 'ps5-hfw',
    title: 'Horizon Forbidden West',
    price: '$50',
    platform: 'PS5',
    img: 'ps5-hfw.jpg',
  },
  {
    id: 'xone-md',
    title: 'Minecraft Dungeons',
    price: '$50',
    platform: 'Xbox',
    img: 'xone-md.jpg',
  },
  {
    id: 'xone-ori',
    title: 'Ori and the Wisps',
    price: '$50',
    platform: 'Xbox',
    img: 'xone-ori.jpg',
  },
  {
    id: 'xone-sot',
    title: 'Sea of Thieves',
    price: '$50',
    platform: 'Xbox',
    img: 'xone-sot.jpg',
  },
  {
    id: 'xone-halo',
    title: 'Halo Infinite',
    price: '$50',
    platform: 'Xbox',
    img: 'xone-halo.jpg',
  },
  {
    id: 'xone-fh5',
    title: 'Forza Horizon 5',
    price: '$50',
    platform: 'Xbox',
    img: 'xone-fh5.jpg',
  },
  {
    id: 's-mk8',
    title: 'Mario Kart 8',
    price: '$50',
    platform: 'Switch',
    img: 's-mk8.jpg',
  },
  {
    id: 's-lm3',
    title: 'Luigi\'s Mansion 3',
    price: '$50',
    platform: 'Switch',
    img: 's-lm3.jpg',
  },
  {
    id: 's-m3d',
    title: 'Mario 3D World',
    price: '$50',
    platform: 'Switch',
    img: 's-m3d.jpg',
  },
  {
    id: 's-bow',
    title: 'Breath of the Wild',
    price: '$50',
    platform: 'Switch',
    img: 's-bow.jpg',
  },
  {
    id: 's-kfl',
    title: 'Kirby Forgotten Land',
    price: '$50',
    platform: 'Switch',
    img: 's-kfl.jpg',
  },
  {
    id: 'pc-outlast',
    title: 'Outlast Trinity',
    price: '$50',
    platform: 'PC',
    img: 'pc-outlast.jpg',
  },
  {
    id: 'pc-boi',
    title: 'The Binding of Isaac',
    price: '$50',
    platform: 'PC',
    img: 'pc-boi.jpg',
  },
  {
    id: 'pc-cc',
    title: 'Castle Crashers',
    price: '$50',
    platform: 'PC',
    img: 'pc-cc.jpg',
  },
  {
    id: 'pc-fc6',
    title: 'Far Cry 6',
    price: '$50',
    platform: 'PC',
    img: 'pc-fc6.jpg',
  },
  {
    id: 'pc-hk',
    title: 'Hollow Knight',
    price: '$50',
    platform: 'PC',
    img: 'pc-hk.jpg',
  }
]